<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ReactivePipelineEditor.Domain\ReactivePipelineEditor.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Execution\" />
    <Folder Include="Executors\" />
    <Folder Include="Metrics\" />
    <Folder Include="Retry\" />
    <Folder Include="Channels\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
